name: build
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '14'
            - run: npm ci
            - run: npm run pack
            - name: save as artifact
              uses: actions/upload-artifact@v2
              with:
                  name: built-extension-zip
                  path: build/*.zip
